<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header $block
 */
 $dataElem =  'some info';

?>

<div class="todo-list" data-bind="scope: 'todo-component'" >
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                        "todo-component": {
                            "component": "Smile_ToDoList/js/view/todo-component",
                            "template": "Smile_ToDoList/todo-component",
                            "config": {
                                "data": "<?php echo $dataElem; ?>"
                            }
                        }
                    }
                }
            }
    }
</script>

