<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()): ?>
        <div class="field qty">
            <label class="label" for="qty"><span><?= /* @escapeNotVerified */ __('Qty') ?></span></label>
            <div class="control">
                <button type="button" class="button-circle" data-role="minus">
                    <span class="but-minus">-</span>
                </button>
                <input type="number"
                       name="qty"
                       id="qty"
                       value="<?= /* @escapeNotVerified */ $block->getProductDefaultQty() * 1 ?>"
                       title="<?= /* @escapeNotVerified */ __('Qty') ?>"
                       class="input-text qty"
                       data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       />
                <button type="button" class="button-circle" data-role="plus">
                    <span class="but-plus">+</span>
                </button>
            </div>
        </div>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?= /* @escapeNotVerified */ $buttonTitle ?>"
                    class="action primary tocart"
                    id="product-addtocart-button">
                <span><?= /* @escapeNotVerified */ $buttonTitle ?></span>
            </button>
            <?= $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
<script>
    require(
        [
            'jquery'
        ],
        function($) {

            $('[data-role="plus"]').click(function(e){
                e.preventDefault();

                var currentVal = parseInt($("input[name='qty']").val());
                if (!isNaN(currentVal)) {
                    $("input[name='qty']").val(currentVal + 1);
                } else {
                    $("input[name='qty']").val(0);
                }
            });

            $('[data-role="minus"]').click(function(e){
                e.preventDefault();

                var currentVal = parseInt($("input[name='qty']").val());

                if (currentVal === 0) {
                    $("input[name='qty']").val(0);
                } else if (!isNaN(currentVal)) {
                    $("input[name='qty']").val(currentVal - 1);
                } else {
                    $("input[name='qty']").val(0);
                }
            });

        }
    );
</script>
